# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27)),
                ('heroku_link', models.CharField(max_length=27)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 10, 13, 13, 49, 16, 725808, tzinfo=utc))),
            ],
        ),
    ]
