# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 12:54
from __future__ import unicode_literals

import add_friend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_friend', '0002_new_friend_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_friend',
            name='created_date',
            field=models.DateTimeField(default=add_friend.models.new_friend.converTime),
        ),
    ]
