# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('add_friend', '0008_auto_20171013_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_friend',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 18, 1, 25, 618965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='new_friend',
            name='heroku_link',
            field=models.CharField(max_length=100),
        ),
    ]
