# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 10, 12, 11, 0, 36, 585390, tzinfo=utc))),
            ],
        ),
    ]
