# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import update_status.models


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(default=update_status.models.Status.converTime),
        ),
    ]
