# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0002_auto_20171011_1437'),
        ('update_status', '0002_auto_20171011_1431'),
    ]

    operations = [
    ]
