# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0007_auto_20171013_1057'),
        ('update_status', '0007_auto_20171013_1228'),
    ]

    operations = [
    ]
