# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0017_auto_20171013_1801'),
        ('update_status', '0008_merge_20171013_1721'),
    ]

    operations = [
    ]
